// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIFrwGMRMaXS7Q8YZVNj5zx-dG7zqkPCs',
    appId: '1:568586437784:web:ce3deaa7aa25897d5c7ced',
    messagingSenderId: '568586437784',
    projectId: 'reddit-649d3',
    authDomain: 'reddit-649d3.firebaseapp.com',
    storageBucket: 'reddit-649d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAoXd_VZb4jDr5IWgbcwEPPO0k64659y4',
    appId: '1:568586437784:android:e2c240b275cc8a1d5c7ced',
    messagingSenderId: '568586437784',
    projectId: 'reddit-649d3',
    storageBucket: 'reddit-649d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL82CtdLnt_yV0yv-E_PQd9HuACZez7lI',
    appId: '1:568586437784:ios:e1d7c827712708745c7ced',
    messagingSenderId: '568586437784',
    projectId: 'reddit-649d3',
    storageBucket: 'reddit-649d3.appspot.com',
    iosClientId: '568586437784-g6nblubmirhqqhfm0od88krs0ajfvvr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
